"use client";
import { ArrowLeft, ArrowUpRight, Check, FileImage, RotateCcw, Upload, X } from "lucide-react";
import { AnimatePresence, motion } from "framer-motion";
import { ChangeEvent, DragEvent, useEffect, useRef, useState } from "react";
import { diseaseConfig, diseaseList, type DiseaseType, type Field } from "@/lib/screening-config";
import { mockInference, type Result } from "@/lib/mock-inference";

type Stage = "select" | "input" | "analyzing" | "result";
const reveal = { initial: { opacity: 0, y: 12 }, animate: { opacity: 1, y: 0 }, exit: { opacity: 0, y: -8 }, transition: { duration: .35 } };

function Topbar() { return <nav className="nav-shell"><a href="/" className="wordmark">[PROJECT NAME]<sup>®</sup></a><div className="screening-nav-label">Research prototype / screening workspace</div><a className="text-link" href="/">Return home <ArrowUpRight size={15}/></a></nav>; }
function Selector({ select }: { select: (id: DiseaseType) => void }) { return <motion.section {...reveal} className="screen-shell"><p className="eyebrow"><span />Screening pathways</p><h1 className="screen-title">Choose a screening<br/><em>pathway.</em></h1><p className="screen-lead">Select the kind of input you would like to review. This prototype uses simulated inference only.</p><div className="disease-grid">{diseaseList.map((disease, index) => <article className="disease-card" key={disease.id}><div><span className="card-index">0{index + 1}</span><p className="card-category">{disease.category}</p></div><h2>{disease.title}</h2><p>{disease.description}</p><div className="card-foot"><span>{disease.input}</span><button onClick={() => select(disease.id)}>{disease.inputType === "image" ? "Upload Image" : "Begin Screening"}<ArrowUpRight size={16}/></button></div></article>)}</div></motion.section>; }
function FormField({ field, value, error, update }: { field: Field; value: string; error?: string; update: (value: string) => void }) { const id = `field-${field.key}`; return <div className={`form-field ${error ? "has-error" : ""}`}><label htmlFor={id}>{field.label}</label>{field.type === "select" ? <select id={id} value={value} onChange={e => update(e.target.value)} aria-invalid={!!error}><option value="">Select an option</option>{field.options?.map(option => <option value={option.value} key={option.value}>{option.label}</option>)}</select> : <div className="number-control"><input id={id} type="number" step={field.step ?? "1"} value={value} onChange={e => update(e.target.value)} aria-invalid={!!error}/>{field.unit && <span>{field.unit}</span>}</div>}{error && <small role="alert">{error}</small>}</div>; }
function TabularForm({ disease, submit }: { disease: DiseaseType; submit: (data: Record<string,string>) => void }) { const config = diseaseConfig[disease]; const [values, setValues] = useState<Record<string,string>>({}); const [errors, setErrors] = useState<Record<string,string>>({});
  const validate = () => { const next: Record<string,string> = {}; config.sections?.flatMap(section => section.fields).forEach(field => { const value = values[field.key]?.trim(); if (!value) next[field.key] = `${field.label} is required.`; else if (field.type === "number" && !Number.isFinite(Number(value))) next[field.key] = `Enter a valid ${field.label.toLowerCase()}.`; }); setErrors(next); return Object.keys(next).length === 0; };
  return <form onSubmit={event => { event.preventDefault(); if (validate()) submit(values); }} noValidate>{config.sections?.map(section => <section className="form-section" key={section.title}><div className="form-section-head"><span>{section.title}</span><small>Required clinical input</small></div><div className="field-grid">{section.fields.map(field => <FormField key={field.key} field={field} value={values[field.key] ?? ""} error={errors[field.key]} update={value => setValues(current => ({...current, [field.key]: value}))}/>)}</div></section>)}<button className="button primary form-submit" type="submit">Run screening <ArrowUpRight size={17}/></button></form>; }
function ImageUpload({ label, submit }: { label: string; submit: (data: Record<string,string>) => void }) { const input = useRef<HTMLInputElement>(null); const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState(""); const [error, setError] = useState(""); useEffect(() => () => { if (preview) URL.revokeObjectURL(preview); }, [preview]);
  const apply = (candidate?: File) => { if (!candidate) return; if (!["image/jpeg", "image/png"].includes(candidate.type)) { setError("Please upload a JPG, JPEG, or PNG image."); return; } if (preview) URL.revokeObjectURL(preview); setFile(candidate); setPreview(URL.createObjectURL(candidate)); setError(""); };
  const choose = (event: ChangeEvent<HTMLInputElement>) => apply(event.target.files?.[0]); const drop = (event: DragEvent<HTMLDivElement>) => { event.preventDefault(); apply(event.dataTransfer.files?.[0]); };
  return <div>{preview ? <div className="image-preview"><img src={preview} alt={`Selected ${label}`} /><div><p>{file?.name}</p><small>Ready for simulated screening</small><div className="preview-actions"><button type="button" onClick={() => input.current?.click()}>Replace image</button><button type="button" onClick={() => { if(preview) URL.revokeObjectURL(preview); setPreview(""); setFile(null); }}>Remove <X size={14}/></button></div></div></div> : <div className="upload-zone" onDragOver={event => event.preventDefault()} onDrop={drop}><FileImage size={29}/><p>Drop a {label} here</p><small>JPG, JPEG or PNG · one image</small><button type="button" onClick={() => input.current?.click()}>Choose image <Upload size={15}/></button></div>}<input ref={input} className="visually-hidden" type="file" accept="image/jpeg,image/png" onChange={choose}/>{error && <p className="upload-error" role="alert">{error}</p>}<button className="button primary form-submit" onClick={() => file ? submit({ image: file.name, size: String(file.size) }) : setError(`Please upload a ${label} before screening.`)}>Run screening <ArrowUpRight size={17}/></button></div>; }
function Analysis({ disease }: { disease: DiseaseType }) { const steps = diseaseConfig[disease].inputType === "image" ? ["Image validated", "Image preprocessing", "Feature extraction", "Model inference", "Screening result"] : ["Input validated", "Feature processing", "Model inference", "Risk analysis", "Screening result"]; return <motion.section {...reveal} className="screen-shell analysis-view"><p className="eyebrow"><span />Simulated inference</p><h1 className="screen-title">Reviewing the<br/><em>input.</em></h1><div className="analysis-steps">{steps.map((step, index) => <motion.div key={step} initial={{ opacity: .25 }} animate={{ opacity: 1 }} transition={{ delay: index * .25 }}><span>0{index + 1}</span><strong>{step}</strong>{index < 4 && <i>↓</i>}</motion.div>)}</div><p>Preparing a deterministic demonstration result. No clinical model is running in this frontend.</p></motion.section>; }
const readable: Record<string,string> = { AKIEC: "Actinic keratoses / intraepithelial carcinoma", BCC: "Basal cell carcinoma", BKL: "Benign keratosis-like lesions", DF: "Dermatofibroma", MEL: "Melanoma", NV: "Melanocytic nevi", VASC: "Vascular lesions", No_DR: "No diabetic retinopathy", Proliferate_DR: "Proliferative diabetic retinopathy" };
function ResultView({ disease, result, data, restart }: { disease: DiseaseType; result: Result; data: Record<string,string>; restart: () => void }) { const config = diseaseConfig[disease]; const image = config.inputType === "image"; const elevated = result.primary.includes("Elevated"); return <motion.section {...reveal} className="screen-shell result-view"><div className="result-kicker"><p className="eyebrow"><span />Screening complete</p><span className="simulation-tag">Demo / simulated</span></div><div className="result-summary"><div><p className="result-context">{config.title} screening</p><h1>{image ? "Screening classification" : result.primary}</h1><p className="result-copy">Based on the supplied screening parameters. This is a research-prototype output, not a diagnosis.</p></div>{!image && <div className={`risk-arc ${elevated ? "elevated" : ""}`}><svg viewBox="0 0 160 92"><path d="M15 78A65 65 0 0 1 145 78"/><path d="M15 78A65 65 0 0 1 112 24"/></svg><span>{elevated ? "Review" : "Lower"}<small>risk indicators</small></span></div>}</div>{result.probabilities ? <div className="probability-panel"><div className="result-panel-label">Class probabilities / simulated</div>{result.probabilities.map(item => <div className="probability" key={item.label}><span>{item.label}</span><div><i style={{width:`${item.value}%`}}/></div><strong>{item.value}%</strong></div>)}</div> : <div className="signal-panel"><div className="result-panel-label">Key input signals / demo visualization</div>{result.signals?.map((signal,index) => <div className="signal" key={signal.label}><i>0{index + 1}</i><span>{signal.label}</span><strong>{signal.value}</strong></div>)}</div>}{image && <div className="image-result"><div><span className="result-panel-label">Original image</span><div className="image-placeholder"><FileImage size={23}/><span>{data.image}</span></div></div><div><span className="result-panel-label">Model attention</span><div className="attention-placeholder">Explainability visualization will be connected to the model backend.<small>DEMO VISUALIZATION</small></div></div></div>}<div className="pipeline result-pipeline"><span>Model processing / simulated inference</span><div><p><b>01 INPUT</b>Clinical features</p><i>→</i><p><b>02 PROCESS</b>Feature encoding</p><i>→</i><p className="quantum-step"><b>03 RESEARCH LAYER</b>Quantum model</p><i>→</i><p><b>04 OUTPUT</b>Risk classification</p></div><small>NO QUANTUM CIRCUIT IS EXECUTED IN THIS FRONTEND</small></div><p className="disclaimer">Research prototype for early screening and decision support. This result is not a medical diagnosis. Please consult a qualified healthcare professional for clinical evaluation.</p><div className="result-actions"><button className="button primary" onClick={restart}>New screening <RotateCcw size={16}/></button><button className="text-link" onClick={restart}>Back to screening selection <ArrowLeft size={16}/></button></div></motion.section>; }
export function ScreeningExperience() { const [stage,setStage] = useState<Stage>("select"); const [disease,setDisease] = useState<DiseaseType | null>(null); const [result,setResult] = useState<Result | null>(null); const [data,setData] = useState<Record<string,string>>({});
  const select = (id: DiseaseType) => { setDisease(id); setStage("input"); }; const run = async (payload: Record<string,string>) => { if(!disease) return; setData(payload); setStage("analyzing"); setResult(await mockInference(disease, payload)); setStage("result"); }; const reset = () => { setDisease(null); setResult(null); setData({}); setStage("select"); };
  return <main className="screening-page"><Topbar/><AnimatePresence mode="wait">{stage === "select" && <Selector key="select" select={select}/>} {stage === "input" && disease && <motion.section {...reveal} className="screen-shell input-view" key="input"><button className="back-button" onClick={reset}><ArrowLeft size={16}/> Back to disease selection</button><p className="eyebrow"><span />{diseaseConfig[disease].category}</p><div className="workspace-heading"><div><h1>{diseaseConfig[disease].title}</h1><p>Clinical screening</p></div><span>{diseaseConfig[disease].input}</span></div><p className="screen-lead">Provide each required input to continue. Missing values are shown explicitly; no clinical values are assumed.</p>{diseaseConfig[disease].inputType === "tabular" ? <TabularForm disease={disease} submit={run}/> : <ImageUpload label={diseaseConfig[disease].uploadLabel!} submit={run}/>}</motion.section>} {stage === "analyzing" && disease && <Analysis key="analysis" disease={disease}/>} {stage === "result" && disease && result && <ResultView key="result" disease={disease} result={result} data={data} restart={reset}/>}</AnimatePresence></main>; }
