export type DiseaseType = "heart" | "ckd" | "retinopathy" | "skinCancer";
export type InputType = "tabular" | "image";
export type Field = { key: string; label: string; type: "number" | "select"; unit?: string; step?: string; options?: { label: string; value: string }[] };
export type FormSection = { title: string; fields: Field[] };
export type DiseaseConfig = { id: DiseaseType; title: string; category: string; description: string; input: string; inputType: InputType; uploadLabel?: string; sections?: FormSection[] };

const yesNo = [{ label: "No", value: "0" }, { label: "Yes", value: "1" }];
const levels = (count: number) => Array.from({ length: count }, (_, value) => ({ label: String(value), value: String(value) }));

export const diseaseConfig: Record<DiseaseType, DiseaseConfig> = {
  heart: { id: "heart", title: "Heart Disease", category: "Clinical data", description: "Screen for heart-disease risk using clinical and cardiac examination parameters.", input: "13 structured clinical features", inputType: "tabular", sections: [
    { title: "Patient profile", fields: [{ key: "age", label: "Age", type: "number", unit: "years" }, { key: "sex", label: "Sex", type: "select", options: [{ label: "Female", value: "0" }, { label: "Male", value: "1" }] }] },
    { title: "Cardiac symptoms", fields: [{ key: "cp", label: "Chest Pain Type", type: "select", options: [{ label: "Typical angina", value: "0" }, { label: "Atypical angina", value: "1" }, { label: "Non-anginal pain", value: "2" }, { label: "Asymptomatic", value: "3" }] }, { key: "exang", label: "Exercise-Induced Angina", type: "select", options: yesNo }] },
    { title: "Vitals", fields: [{ key: "trestbps", label: "Resting Blood Pressure", type: "number", unit: "mmHg" }, { key: "chol", label: "Serum Cholesterol", type: "number", unit: "mg/dL" }, { key: "fbs", label: "Fasting Blood Sugar > 120 mg/dL", type: "select", options: yesNo }, { key: "thalach", label: "Maximum Heart Rate", type: "number", unit: "bpm" }] },
    { title: "ECG / exercise", fields: [{ key: "restecg", label: "Resting ECG", type: "select", options: [{ label: "Normal", value: "0" }, { label: "ST-T wave abnormality", value: "1" }, { label: "Probable/definite LV hypertrophy", value: "2" }] }, { key: "oldpeak", label: "ST Depression", type: "number", step: "0.1" }, { key: "slope", label: "ST Segment Slope", type: "select", options: [{ label: "Upsloping", value: "0" }, { label: "Flat", value: "1" }, { label: "Downsloping", value: "2" }] }, { key: "ca", label: "Major Vessels", type: "select", options: levels(4) }, { key: "thal", label: "Thalassemia", type: "select", options: [{ label: "Normal", value: "1" }, { label: "Fixed defect", value: "2" }, { label: "Reversible defect", value: "3" }] }] }
  ] },
  ckd: { id: "ckd", title: "Chronic Kidney Disease", category: "Clinical + lab data", description: "Screen for CKD using blood, urine, physiological and clinical indicators.", input: "24 structured features", inputType: "tabular", sections: [
    { title: "Patient profile", fields: [{ key: "age", label: "Age", type: "number", unit: "years" }, { key: "bp", label: "Blood Pressure", type: "number", unit: "mmHg" }] },
    { title: "Urine analysis", fields: [{ key: "sg", label: "Specific Gravity", type: "select", options: ["1.005", "1.010", "1.015", "1.020", "1.025"].map(value => ({ label: value, value })) }, { key: "al", label: "Albumin level", type: "select", options: levels(6) }, { key: "su", label: "Urine sugar level", type: "select", options: levels(6) }, { key: "rbc", label: "Red Blood Cells", type: "select", options: [{ label: "Normal", value: "normal" }, { label: "Abnormal", value: "abnormal" }] }, { key: "pc", label: "Pus Cell", type: "select", options: [{ label: "Normal", value: "normal" }, { label: "Abnormal", value: "abnormal" }] }, { key: "pcc", label: "Pus Cell Clumps", type: "select", options: [{ label: "Not present", value: "notpresent" }, { label: "Present", value: "present" }] }, { key: "ba", label: "Bacteria", type: "select", options: [{ label: "Not present", value: "notpresent" }, { label: "Present", value: "present" }] }] },
    { title: "Blood tests", fields: [{ key: "bgr", label: "Random Blood Glucose", type: "number", unit: "mg/dL" }, { key: "bu", label: "Blood Urea", type: "number", unit: "mg/dL" }, { key: "sc", label: "Serum Creatinine", type: "number", unit: "mg/dL", step: "0.1" }, { key: "sod", label: "Sodium", type: "number", unit: "mEq/L" }, { key: "pot", label: "Potassium", type: "number", unit: "mEq/L", step: "0.1" }, { key: "hemo", label: "Hemoglobin", type: "number", unit: "g/dL", step: "0.1" }, { key: "pcv", label: "Packed Cell Volume", type: "number", unit: "%" }, { key: "wc", label: "White Blood Cell Count", type: "number", unit: "cells/cumm" }, { key: "rc", label: "Red Blood Cell Count", type: "number", unit: "millions/cmm", step: "0.1" }] },
    { title: "Clinical history", fields: [{ key: "htn", label: "Hypertension", type: "select", options: [{ label: "No", value: "no" }, { label: "Yes", value: "yes" }] }, { key: "dm", label: "Diabetes Mellitus", type: "select", options: [{ label: "No", value: "no" }, { label: "Yes", value: "yes" }] }, { key: "cad", label: "Coronary Artery Disease", type: "select", options: [{ label: "No", value: "no" }, { label: "Yes", value: "yes" }] }, { key: "appet", label: "Appetite", type: "select", options: [{ label: "Good", value: "good" }, { label: "Poor", value: "poor" }] }, { key: "pe", label: "Pedal Edema", type: "select", options: [{ label: "No", value: "no" }, { label: "Yes", value: "yes" }] }, { key: "ane", label: "Anemia", type: "select", options: [{ label: "No", value: "no" }, { label: "Yes", value: "yes" }] }] }
  ] },
  retinopathy: { id: "retinopathy", title: "Diabetic Retinopathy", category: "Retinal image", description: "Screen a retinal fundus image for diabetic retinopathy severity.", input: "Retinal image", inputType: "image", uploadLabel: "retinal fundus image" },
  skinCancer: { id: "skinCancer", title: "Skin Cancer", category: "Dermoscopic image", description: "Screen a dermoscopic skin-lesion image across seven lesion categories.", input: "Dermoscopic image", inputType: "image", uploadLabel: "dermoscopic skin-lesion image" }
};

export const diseaseList = Object.values(diseaseConfig);
