export type DiseaseType = "heart" | "diabetes" | "retinopathy" | "skinCancer";
export type InputType = "tabular" | "image";
export type Field = { key: string; label: string; type: "number" | "select"; unit?: string; step?: string; min?: number; max?: number; options?: { label: string; value: string }[] };
export type FormSection = { title: string; fields: Field[] };
export type DiseaseConfig = { id: DiseaseType; title: string; category: string; description: string; input: string; inputType: InputType; uploadLabel?: string; sections?: FormSection[] };

const yesNo = [{ label: "No", value: "0" }, { label: "Yes", value: "1" }];
const levels = (count: number) => Array.from({ length: count }, (_, value) => ({ label: String(value), value: String(value) }));
const ageGroups = ["18–24", "25–29", "30–34", "35–39", "40–44", "45–49", "50–54", "55–59", "60–64", "65–69", "70–74", "75–79", "80+"].map((label, index) => ({ label, value: String(index + 1) }));

export const diseaseConfig: Record<DiseaseType, DiseaseConfig> = {
  heart: { id: "heart", title: "Heart Disease", category: "Clinical data", description: "Screen for heart-disease risk using clinical and cardiac examination parameters.", input: "13 structured clinical features", inputType: "tabular", sections: [
    { title: "Patient profile", fields: [{ key: "age", label: "Age", type: "number", unit: "years" }, { key: "sex", label: "Sex", type: "select", options: [{ label: "Female", value: "0" }, { label: "Male", value: "1" }] }] },
    { title: "Cardiac symptoms", fields: [{ key: "cp", label: "Chest Pain Type", type: "select", options: [{ label: "Typical angina", value: "0" }, { label: "Atypical angina", value: "1" }, { label: "Non-anginal pain", value: "2" }, { label: "Asymptomatic", value: "3" }] }, { key: "exang", label: "Exercise-Induced Angina", type: "select", options: yesNo }] },
    { title: "Vitals", fields: [{ key: "trestbps", label: "Resting Blood Pressure", type: "number", unit: "mmHg" }, { key: "chol", label: "Serum Cholesterol", type: "number", unit: "mg/dL" }, { key: "fbs", label: "Fasting Blood Sugar > 120 mg/dL", type: "select", options: yesNo }, { key: "thalach", label: "Maximum Heart Rate", type: "number", unit: "bpm" }] },
    { title: "ECG / exercise", fields: [{ key: "restecg", label: "Resting ECG", type: "select", options: [{ label: "Normal", value: "0" }, { label: "ST-T wave abnormality", value: "1" }, { label: "Probable/definite LV hypertrophy", value: "2" }] }, { key: "oldpeak", label: "ST Depression", type: "number", step: "0.1" }, { key: "slope", label: "ST Segment Slope", type: "select", options: [{ label: "Upsloping", value: "0" }, { label: "Flat", value: "1" }, { label: "Downsloping", value: "2" }] }, { key: "ca", label: "Major Vessels", type: "select", options: levels(4) }, { key: "thal", label: "Thalassemia", type: "select", options: [{ label: "Normal", value: "1" }, { label: "Fixed defect", value: "2" }, { label: "Reversible defect", value: "3" }] }] }
  ] },
  diabetes: { id: "diabetes", title: "Diabetes", category: "Clinical / lifestyle data", description: "Assess diabetes-related risk indicators using health, lifestyle, and clinical information.", input: "Selected health and lifestyle indicators", inputType: "tabular", sections: [
    { title: "Health profile", fields: [{ key: "Age", label: "Age Group", type: "select", options: ageGroups }, { key: "Sex", label: "Sex", type: "select", options: [{ label: "Female", value: "0" }, { label: "Male", value: "1" }] }, { key: "BMI", label: "BMI", type: "number", step: "0.1" }, { key: "GenHlth", label: "General Health", type: "select", options: [{ label: "Excellent", value: "1" }, { label: "Very Good", value: "2" }, { label: "Good", value: "3" }, { label: "Fair", value: "4" }, { label: "Poor", value: "5" }] }] },
    { title: "Clinical history", fields: [{ key: "HighBP", label: "High Blood Pressure", type: "select", options: yesNo }, { key: "HighChol", label: "High Cholesterol", type: "select", options: yesNo }, { key: "CholCheck", label: "Cholesterol Checked", type: "select", options: yesNo }, { key: "Stroke", label: "History of Stroke", type: "select", options: yesNo }, { key: "HeartDiseaseorAttack", label: "Heart Disease / Heart Attack", type: "select", options: yesNo }, { key: "DiffWalk", label: "Difficulty Walking", type: "select", options: yesNo }] },
    { title: "Lifestyle", fields: [{ key: "Smoker", label: "Smoker", type: "select", options: yesNo }, { key: "PhysActivity", label: "Physical Activity", type: "select", options: yesNo }, { key: "Fruits", label: "Regular Fruit Consumption", type: "select", options: yesNo }, { key: "Veggies", label: "Regular Vegetable Consumption", type: "select", options: yesNo }, { key: "HvyAlcoholConsump", label: "Heavy Alcohol Consumption", type: "select", options: yesNo }] },
    { title: "Health access / wellbeing", fields: [{ key: "AnyHealthcare", label: "Has Healthcare Coverage", type: "select", options: yesNo }, { key: "NoDocbcCost", label: "Could Not See Doctor Due to Cost", type: "select", options: yesNo }, { key: "MentHlth", label: "Poor Mental Health Days", type: "number", unit: "days", step: "1", min: 0, max: 30 }, { key: "PhysHlth", label: "Poor Physical Health Days", type: "number", unit: "days", step: "1", min: 0, max: 30 }] }
  ] },
  retinopathy: { id: "retinopathy", title: "Diabetic Retinopathy", category: "Retinal image", description: "Screen a retinal fundus image for diabetic retinopathy severity.", input: "Retinal image", inputType: "image", uploadLabel: "retinal fundus image" },
  skinCancer: { id: "skinCancer", title: "Skin Cancer", category: "Dermoscopic image", description: "Screen a dermoscopic skin-lesion image across seven lesion categories.", input: "Dermoscopic image", inputType: "image", uploadLabel: "dermoscopic skin-lesion image" }
};

export const diseaseList = Object.values(diseaseConfig);
